language: clojure

before_script:
    - lein cljsbuild once

before_install:
    - npm install lumo-cljs@1.8.0 -g

script:
    - lein test :yes-i-know-the-tests-are-supposed-to-fail 2>&1 | diff test/fixtures/test_output -
    - >
      lein doo phantom test once 2>&1 |
      | grep --invert-match 'TypeError'
      | grep --invert-match 'Subprocess'
      | grep --invert-match ';;'
      | sed -e 's/(cljs\/test\.js.*)/(:)/'
      | tail -n +4
      | diff test/fixtures/test_output_cljs -
    - >
      lumo -c $(lein classpath) -i test/pjstadig/run_self_host.cljs -e '(pjstadig.run-self-host/run)'
      | sed -e 's/(at evalmachine.<anonymous>.*)/(:)/'
      | diff test/fixtures/test_output_cljs -
