language: clojure

before_install:
    - npm install lumo-cljs@1.8.0 -g

script:
    - lein test :yes-i-know-the-tests-are-supposed-to-fail 2>&1 | diff test/fixtures/test_output -
    - ./.travis/phantom-test
    - ./.travis/lumo-test
